name: Build and Test app
on: 
  push:
    branches: [develop]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'LearningSwiftUI.xcworkspace' }}
      XC_SCHEME: ${{ 'LearningSwiftUI' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
